### ISSUE TITLE
KanBan Setup 🧮

### ISSUE THREAD

**Issue by hsztan** [hsztan/RecipeApp#8]
- [Project Link ](https://github.com/users/hsztan/projects/6)
- We are 2 awesome developers 😁

> Note: Plz Review with love 😌

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @hsztan and @fasaldana,

Good job so far!
✔️ Kanban board columns are correctly set up
✔️ Tasks have descriptions and are properly assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] I can't find any tasks that address these two requirements. Kindly add them.

  ![navigation-1](https://user-images.githubusercontent.com/36542986/180828674-a7ccab80-3172-4cc8-95d0-54a12722edec.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by hsztan** [comment]
@TedLivist You can kindly now find them 🤓

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- Descriptive information ✔️
- Tasks are distributed equally ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
